[build]
builder = "nixpacks"

[deploy]
startCommand = "python src/main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[deploy.envs]
PYTHONPATH = "/app/src"
LOBBY_HTTP_PORT = "8080"
LOBBY_WS_PORT = "8081"
ENVIRONMENT = "production" 