[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -m src.railway_main"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[experimental]
incrementalDeploy = true

[[services]]
name = "agent-lobbi-backend"

[services.variables]
PORT = "8080"
LOBBY_HTTP_PORT = "8080"
LOBBY_WS_PORT = "8081"
DATABASE_URL = "${{ Postgres.DATABASE_URL }}"
REDIS_URL = "${{ Redis.REDIS_URL }}"
ENV = "production"
LOG_LEVEL = "INFO"
CORS_ORIGINS = "*"
API_BASE_URL = "https://agent-lobbi-backend.up.railway.app"
MAX_WORKERS = "4" 